export const EMIT_FULL_PAGE_REQUEST_LOADING = "EMIT_FULL_PAGE_REQUEST_LOADING";
export const EMIT_TOGGLE_MASK = "EMIT_TOGGLE_MASK";
export const EMIT_TOGGLE_RECORD_MATCH_MODAL = "EMIT_TOGGLE_RECORD_MATCH_MODAL";
