export const EMIT_GET_PLAYER_SEARCH_RESULTS_SUCCESS = "EMIT_GET_PLAYER_SEARCH_RESULTS_SUCCESS";
export const EMIT_SEARCHING_FOR_PLAYERS = "EMIT_SEARCHING_FOR_PLAYERS";
export const EMIT_GET_PLAYERS_SUCCESS = "EMIT_GET_PLAYERS_SUCCESS";
export const EMIT_CREATE_PLAYER_SUCCESS = "EMIT_CREATE_PLAYER_SUCCESS";
export const EMIT_CLEAR_PLAYER_LIST = "EMIT_CLEAR_PLAYER_LIST";
