export const EMIT_GET_ACTIVE_PLAYERS_SUCCESS = "MIT_GET_ACTIVE_PLAYERS_SUCCESS";
export const EMIT_GET_DEFENDING_PLAYERS_SUCCESS = "MIT_GET_DEFENDING_PLAYERS_SUCCESS";
export const EMIT_SEARCHING_FOR_ACTIVE_PLAYERS = "MIT_SEARCHING_FOR_ACTIVE_PLAYERS";
export const EMIT_SEARCHING_FOR_DEFENDING_PLAYERS = "MIT_SEARCHING_FOR_DEFENDING_PLAYERS";
export const EMIT_GET_PLAYERS_SUCCESS = "EMIT_GET_PLAYERS_SUCCESS";
export const EMIT_CREATE_PLAYER_SUCCESS = "EMIT_CREATE_PLAYER_SUCCESS";
