export const EMIT_GET_POTENTIAL_PLAYER_A_SUCCESS = "EMIT_GET_POTENTIAL_PLAYER_A_SUCCESS";
export const EMIT_GET_POTENTIAL_PLAYER_B_SUCCESS = "EMIT_GET_POTENTIAL_PLAYER_B_SUCCESS";
export const EMIT_SEARCHING_FOR_ACTIVE_PLAYERS = "EMIT_SEARCHING_FOR_ACTIVE_PLAYERS";
export const EMIT_SEARCHING_FOR_DEFENDING_PLAYERS = "EMIT_SEARCHING_FOR_DEFENDING_PLAYERS";
export const EMIT_GET_PLAYERS_SUCCESS = "EMIT_GET_PLAYERS_SUCCESS";
export const EMIT_CREATE_PLAYER_SUCCESS = "EMIT_CREATE_PLAYER_SUCCESS";
export const EMIT_CLEAR_PLAYER_A_LIST = "EMIT_CLEAR_PLAYER_A_LIST";
export const EMIT_CLEAR_PLAYER_B_LIST = "EMIT_CLEAR_PLAYER_B_LIST";
