export const EMIT_CREATE_SEASON_SUCCESS = "EMIT_CREATE_SEASON_SUCCESS";
export const EMIT_GET_SEASONS_SUCCESS = "EMIT_GET_SEASONS_SUCCESS";
export const EMIT_SELECTED_SEASON = "EMIT_SELECTED_SEASON";
export const EMIT_DESELECTED_SEASON = "EMIT_DESELECTED_SEASON";
