export const REQUEST_APPLICATION = 'REQUEST_APPLICATION';
export const REQUEST_AUTH = 'REQUEST_AUTH';
export const REQUEST_GETTING_STARTED = 'REQUEST_GETTING_STARTED';
export const REQUEST_USER = 'REQUEST_USER';
