export const REQUEST_APPLICATION = "REQUEST_APPLICATION";
export const REQUEST_AUTH = "REQUEST_AUTH";
export const REQUEST_GETTING_STARTED_CARDS = "REQUEST_GETTING_STARTED_CARDS";
export const REQUEST_GETTING_STARTED_PLAYER = "REQUEST_GETTING_STARTED_PLAYER";
export const REQUEST_RECORD_MATCH = "REQUEST_RECORD_MATCH";
export const REQUEST_USER = "REQUEST_USER";
