export const EMIT_GETTING_STARTED_CARDS_SUCCESS = "EMIT_GETTING_STARTED_CARDS_SUCCESS";
export const EMIT_SETS_SUCCESS = "EMIT_SETS_SUCCESS";
export const EMIT_SEARCHING_FOR_SET = "EMIT_SEARCHING_FOR_SET";
