export const EMIT_CREATE_MATCH_SUCCESS = "EMIT_CREATE_MATCH_SUCCESS";
export const EMIT_UPDATE_LOADING_MATCHES = "EMIT_UPDATE_LOADING_MATCHES";
export const EMIT_UPDATE_LOADING_MATCH_CREATION = "EMIT_UPDATE_LOADING_MATCH_CREATION";
export const EMIT_GET_MATCH_SEARCH_RESULTS = "EMIT_GET_MATCH_SEARCH_RESULTS";
export const EMIT_GET_MATCH_SEARCH_RESULTS_SUCCESS = "EMIT_GET_MATCH_SEARCH_RESULTS_SUCCESS";
